[[redirects]]
  from = "https://resume.aaronjanovitch.com"
  to = "https://aaronjanovitch.com/Aaron-Janovitch-Resume.pdf"
  status = 200
  headers = {
    Content-Disposition = "inline; filename=Aaron-Janovitch-Resume.pdf"
  }
