[[redirects]]
  from = "https://resume.aaronjanovitch.com/*"
  to = "/netlify/functions/redirect.js"
  status = 200
  force = true

[[headers]]
  for = "/netlify/functions/redirect.js"
  [headers.values]
    Content-Disposition = "inline; filename=Aaron-Janovitch-Resume.pdf"

